### ISSUE TITLE
Multihost deployment

### ISSUE THREAD

**Issue by yamani** [hectordufau/dockerfabricwizard#1]
kindly advice if we can tweek the tool you created to support Docker Swarm or Multi-host Docker deployment. for example each Org is on specific VM.

**Comment by hectordufau** [comment]
Sure! All contributions are welcome!

However, after create a network using Docker Fabric Wizard, you can check domains\[DOMAINNAME]\compose to get docker compose yaml files to up hosts. 
![image](https://github.com/hectordufau/dockerfabricwizard/assets/12888215/08b7e8ae-020c-4925-908d-a654c3cff9f5)

I have plans to export scripts to start blockchain and etc.

Fell free to use it.
