### ISSUE TITLE
TLS Handshake error at peer after trying to invoke chaincode via fabric SDK

### ISSUE THREAD

**Issue by AmeerRiyaz** [hectordufau/dockerfabricwizard#2]
Created connection profile for a org and using fabric SDK sucessfully created an admin identity along with an user in an wallet , After that while invoking the chaincode through SDK getting Discovery error and cannot connect through the fabric Gateway , After checking peer logs could find that we are getting TLS handshake error replaced the TLS certs with differnt certs generated through the script , If you can guide us will be helpful 
![WhatsApp Image 2023-10-23 at 16 57 12_545f55eb](https://github.com/hectordufau/dockerfabricwizard/assets/87801344/04abcaba-3e57-4e52-ba4d-6d183cbb26fd)
![WhatsApp Image 2023-10-23 at 16 57 12_dc7f5c06](https://github.com/hectordufau/dockerfabricwizard/assets/87801344/ed9b6ec9-726b-4ab3-83e7-4496c290c77b)

**Comment by hectordufau** [comment]
please, run "docker ps -a" and send your result here.

**Comment by AmeerRiyaz** [comment]
![WhatsApp Image 2023-10-23 at 17 06 25_6128df9c](https://github.com/hectordufau/dockerfabricwizard/assets/87801344/e7a28d18-7a93-4f42-8a43-0f4b975c1746)

**Comment by AmeerRiyaz** [comment]
![WhatsApp Image 2023-10-23 at 17 08 37_baadc6b7](https://github.com/hectordufau/dockerfabricwizard/assets/87801344/d768fe84-291d-4942-a70f-e1aebc8be29f)

which certificate path should i replace here with

**Comment by hectordufau** [comment]
Please, list and show your Docker Fabric domains/example.com folders

**Comment by shubhamacharya** [comment]
[example.com.txt](https://github.com/hectordufau/dockerfabricwizard/files/13069609/example.com.txt)

**Comment by hectordufau** [comment]
The peer0.org0 tlsCACert path is in 

`peerOganizations/org0/peer1.org0/tls/tlscacerts/tls-cert.pem`

Your connection profile config file is using variables, take care with them to reflect the right path of this cert file for each peer

If docker is running in your host, use "localhost" instead of an IP address.

**Comment by hectordufau** [comment]
An important detail: Docker Fabric Wizard doesn't create a first peer on each org with zero (0) in its name.....always start with 1.

Take a look in your "docker ps -a" command and in your folder list results.

**Comment by hectordufau** [comment]
A tip: Take a look on domains/<yourdomain>/setup.json file

organizations/peers/<peer>/volumes shows the whole path for certicate files used by each peer.
